name       : gettext
version    : 0.19.8.1
release    : 5
source     :
    - http://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.gz : ff942af0e438ced4a8b0ea4b0b6e0d6d657157c5e2364de57baa279c1c125c43
homepage   : http://www.gnu.org
license    : GPL-3.0
component  : system.base
summary    : Localisation support for programs
description: |
    The Gettext package contains utilities for internationalization and localization. These allow programs to be compiled with NLS (Native Language Support), enabling them to output messages in the user's native language.
builddeps  :
    - pkgconfig(libpcre)
    - attr-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
