name       : gettext
version    : 0.20.2
release    : 13
source     :
    - https://ftp.gnu.org/gnu/gettext/gettext-0.20.2.tar.xz : b22b818e644c37f6e3d1643a1943c32c3a9bff726d601e53047d2682019ceaba
homepage   : https://www.gnu.org/software/gettext
license    : GPL-3.0-or-later
component  : system.base
summary    : Localisation support for programs
description: |
    The Gettext package contains utilities for internationalization and localization. These allow programs to be compiled with NLS (Native Language Support), enabling them to output messages in the user's native language.
autodep    : false
libsplit   : false
builddeps  :
    - pkgconfig(libattr)
    - pkgconfig(libpcre)
patterns   :
    - docs : /usr/share/doc
    - devel : /usr/share/man/man3
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
