name       : gettext
version    : 0.20.1
release    : 12
source     :
    - https://ftp.gnu.org/gnu/gettext/gettext-0.20.1.tar.xz : 53f02fbbec9e798b0faaf7c73272f83608e835c6288dd58be6c9bb54624a3800
homepage   : https://www.gnu.org/software/gettext
license    : GPL-3.0-or-later
component  : system.base
summary    : Localisation support for programs
autodep    : false
devel      : true
libsplit   : false
description: |
    The Gettext package contains utilities for internationalization and localization. These allow programs to be compiled with NLS (Native Language Support), enabling them to output messages in the user's native language.
builddeps  :
    - pkgconfig(libpcre)
    - attr-devel
patterns   :
    - docs : /usr/share/doc
    - devel : /usr/share/man/man3
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
