name       : gettext
version    : '0.21'
release    : 14
source     :
    - https://ftp.gnu.org/gnu/gettext/gettext-0.21.tar.gz : c77d0da3102aec9c07f43671e60611ebff89a996ef159497ce8e59d075786b12
homepage   : https://www.gnu.org/software/gettext
license    : GPL-3.0-or-later
component  : system.base
summary    : Localisation support for programs
description: |
    The Gettext package contains utilities for internationalization and localization. These allow programs to be compiled with NLS (Native Language Support), enabling them to output messages in the user's native language.
autodep    : false
libsplit   : false
builddeps  :
    - pkgconfig(libattr)
    - pkgconfig(libpcre)
patterns   :
    - docs : /usr/share/doc
    - devel : /usr/share/man/man3
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
